### PR TITLE
Multichannel Support!

### PR DESCRIPTION
**Pull request by IoTPanic**
**Adding Channels**
Now you may connect a channel to the pixels object by using the `bool addChannel(int dataPin, unsigned cnt, uint8_t chan);` which will construct a new neopixel lib instance and add it to an array. When a pixels packet arrives with that channel number in the header, it should show on the strip assigned to that channel.

**Next Step**
Please test with one and multiple strips. This will be merged when that has been completed.

### CODE REVIEW

**Comment by IoTPanic** [comment]
Should add to return false if there is already a strip attached with same channel number

**Review by martinberlin — APPROVED** [review]

**Comment by martinberlin** [comment]
Thanks Samuel looks great. Now question: 
Channel comes then as the 2 byte right, after the 'p'. Now can you please document this part in the Readme and then also make a small .bin example that we can send with Netcat and test this?

I would like to have a very simple example of sending 3 pixels to channel 1,2,3 on any color, or maybe just first Pixel only Red to channel 1, Green to 2 and Blue to 3. I assume it's possible to send them concatenated using the same length but still did not went line by line. Will test it as soon as possible!
This opens a lot more possibilities!

**Comment by IoTPanic** [comment]
I did not make them so they can be concatenated. I will add examples shortly.

**Comment by martinberlin** [comment]
No problem I will test this first without sending it concatenated. Then will give it a second round of though :)

**Pull request closed without merging**
